name: grow_food
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_screenutil: ^5.6.0
  flutter_svg: ^1.1.6
  scale_button: ^2.1.2
  equatable: ^2.0.5
  dartz: ^0.10.1
  flutter_bloc: ^8.1.1
  get_it: ^7.2.0
  dio: ^4.0.6
  pretty_dio_logger: ^1.2.0-beta-1
  cupertino_icons: ^1.0.2
  flutter_smart_dialog: ^4.2.5
  flutter_secure_storage: ^6.1.0
  flutter_native_splash: ^2.2.18
  http: ^0.13.5
  regexpattern: ^2.1.0
  mask_text_input_formatter: ^2.4.0
  hydrated_bloc: ^9.1.0
  path_provider: ^2.0.14
  youtube_player_flutter: ^8.1.2
  cached_network_image: ^3.2.3
  card_loading: ^0.3.0
  modal_bottom_sheet: ^2.1.2
  image_picker: ^0.8.7+3
  duration: ^3.0.12
  onesignal_flutter: ^3.5.1
  url_launcher: ^6.1.7
  firebase_dynamic_links: ^5.1.1
  firebase_core: ^2.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter_native_splash:
  image: assets/images/like.png
  color: "#2E3190"
  image_dark: assets/images/like.png
  color_dark: "#2E3190"
  android_12:
    color: "#2E3190"
    color_dark: "#2E3190"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/json/

  fonts:
    - family: Mons
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
