name: grow_food
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_screenutil: ^5.6.0
  flutter_svg: ^1.1.6
  scale_button: ^2.1.2

  cupertino_icons: ^1.0.2
  flutter_smart_dialog: ^4.8.2+5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Mons
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        
